-- CreateEnum
CREATE TYPE "Department" AS ENUM ('AUP', 'OUOKR', 'OKS', 'YO', 'OSIOOR', 'OOEFP', 'PTO', 'OERO', 'OSO', 'OOOVVO', 'OOOKHVK', 'MP', 'OOSPB', 'OOOR', 'OHO');

-- CreateEnum
CREATE TYPE "Specialty" AS ENUM ('HEAD', 'SERVICE_CHIEF', 'DEPUTY_HEAD', 'DEPARTMENT_CHIEF', 'DEPUTY_DEPARTMENT_CHIEF', 'CHIEF_SPECIALIST', 'CHIEF_SPECIALIST_ENGINEER', 'CHIEF_SPECIALIST_AGRONOMIST', 'CHIEF_SPECIALIST_LABOR', 'CHIEF_SPECIALIST_MASTER', 'LEAD_SPECIALIST', 'LEAD_SPECIALIST_ENGINEER', 'LEAD_SPECIALIST_MASTER', 'LEAD_SPECIALIST_MECHANIC', 'LEAD_SPECIALIST_OPERATOR', 'LEAD_SPECIALIST_LABOR', 'LEAD_SPECIALIST_HVAC', 'SPECIALIST_1', 'SPECIALIST_1_OPERATOR', 'SPECIALIST_1_DUTY', 'SPECIALIST_1_PARAMEDIC', 'CHIEF_SPECIALIST_HALF_RATE', 'ELECTRICIAN', 'PLUMBER', 'LOCKSMITH_REPAIRMAN', 'LOCKSMITH_REPAIRMAN_KIPIA', 'LOCKSMITH_VENTILATION', 'WELDER', 'DRIVER', 'DOCTOR', 'WAREHOUSE_KEEPER', 'ADMINISTRATOR', 'PAINTER', 'CLEANER', 'AUXILIARY_WORKER', 'GREEN_WORKER');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "department" "Department",
ADD COLUMN     "speciality" "Specialty";
