export const SPECIALTY_LABELS: Record<string, string> = {
    HEAD: 'Руководитель',
    SERVICE_CHIEF: 'Начальник службы',
    DEPUTY_HEAD: 'Заместитель руководителя',
    DEPARTMENT_CHIEF: 'Начальник отдела',
    DEPUTY_DEPARTMENT_CHIEF: 'Заместитель начальника отдела',
    CHIEF_SPECIALIST: 'Главный специалист',
    CHIEF_SPECIALIST_ENGINEER: 'Главный специалист, инженер',
    CHIEF_SPECIALIST_AGRONOMIST: 'Начальник отдела, главный агроном',
    CHIEF_SPECIALIST_LABOR: 'Главный специалист, специалист по охране труда',
    CHIEF_SPECIALIST_MASTER: 'Главный специалист, мастер',
    LEAD_SPECIALIST: 'Ведущий специалист',
    LEAD_SPECIALIST_ENGINEER: 'Ведущий специалист, инженер',
    LEAD_SPECIALIST_MASTER: 'Ведущий специалист, мастер',
    LEAD_SPECIALIST_MECHANIC: 'Ведущий специалист, механизатор',
    LEAD_SPECIALIST_OPERATOR: 'Ведущий специалист, оператор ПУ',
    LEAD_SPECIALIST_LABOR: 'Ведущий специалист, специалист по охране труда',
    LEAD_SPECIALIST_HVAC: 'Ведущий специалист, машинист ХУ',
    SPECIALIST_1: 'Специалист 1 категории',
    SPECIALIST_1_OPERATOR: 'Специалист 1 категории, оператор пульта ПС',
    SPECIALIST_1_DUTY: 'Специалист 1 категории, дежурный',
    SPECIALIST_1_PARAMEDIC: 'Специалист 1 категории (фельдшер)',
    CHIEF_SPECIALIST_HALF_RATE: 'Главный специалист на 0,5 ставки',
    ELECTRICIAN: 'Электромонтёр по ремонту и обслуживанию электрооборудования',
    PLUMBER: 'Слесарь-сантехник',
    LOCKSMITH_REPAIRMAN: 'Слесарь-ремонтник',
    LOCKSMITH_REPAIRMAN_KIPIA: 'Слесарь-ремонтник, слесарь КИПиА',
    LOCKSMITH_VENTILATION: 'Слесарь по ремонту и обслуживанию систем вентиляции, кондиционирования',
    WELDER: 'Электрогазосварщик',
    DRIVER: 'Водитель автомобиля',
    DOCTOR: 'Врач',
    WAREHOUSE_KEEPER: 'Кладовщик',
    ADMINISTRATOR: 'Администратор',
    PAINTER: 'Маляр',
    CLEANER: 'Уборщик производственных и служебных помещений',
    AUXILIARY_WORKER: 'Подсобный рабочий',
    GREEN_WORKER: 'Рабочий зеленого хозяйства',
} as const;
